### ISSUE TITLE
SIM card not found on samsung galaxy s4 sph-l720 under [JDCTeam][6.0.1][10 September][OMS-Substratum]

### ISSUE THREAD

**Issue by kratovonar** [AOSP-JF-MM/issue_tracking_aosp#90] opened 2016-09-30 14:49 UTC
Hi, I just flashed your rom to my galaxy s4 sph-l720 and, everything works fine apart from the sim card that says to insert, even though my simcard is placed in my phone, can you tell me which info or log I need to send to you?

**Comment by codeseven58** [comment] 2016-11-14 04:56
2 things, if your phone starts up and it doesnt show the sim card is present, reset the phone. This was a small bug that would show the sim csrd on tue second start. Also, upgrade to the october release and report back with conclusion.

Other thing is if the sim card does work, but randomly disconnects while youre using it, then you have a hardware related issue that can only be fixed by opening your phone and placing a piece of foam over the connector for the sd and simm card then closing up your phone. There aretutorials for this online, google it.

**Comment by kratovonar** [comment] 2016-11-14 08:55
Thank you very much, the october release is much more better and stable I
think, everything works fine now

**Comment by codeseven58** [comment] 2016-11-15 02:55
If you would be so kind as to close this issue, the community and devs would greatly appreciate it. Thank you in advance :)

**Comment by Suncatcher** [comment] 2017-03-05 11:33
I flashed the latest firmware from 22.02 on my L720 and have exactly the same problem. My SIM-card is not recognized.
Where can I download old builds to try?

**Comment by smeroni68** [comment] 2017-03-05 11:50
Check newly on romhut... now it's visible. Let us know if the old build solve or not. Thanks

**Comment by Suncatcher** [comment] 2017-03-05 13:11
> Let us know if the old build solve or not

Nope, that haven't helped. The same result also on 17/11 build. Maybe worth to try October's release, kratovonar [wrote](https://github.com/AOSP-JF-MM/issue_tracking_aosp/issues/90#issuecomment-260280691) about?

**Comment by Suncatcher** [comment] 2017-03-05 13:23
What baseband version should I have for your ROM to work? Now it's L720VPUGPI2

**Comment by Suncatcher** [comment] 2017-03-05 13:32
Flashed the Stock_kernel from you page, but that didn't help anyway.

**Comment by smeroni68** [comment] 2017-03-05 13:36
Flash latest stock rom for your model to check if sim detection is working.

**Comment by Suncatcher** [comment] 2017-03-05 13:38
> Flash latest stock rom for your model to check if sim detection is working.

Perfectly working. I had  L720VPUGPI2_L720SPTGPI2_SPR before and it worked.

**Comment by smeroni68** [comment] 2017-03-05 16:08
Is your phone/network CDMA or GSM?

**Comment by Suncatcher** [comment] 2017-03-05 16:14
> Is your phone/network CDMA or GSM?

GSM. 
BTW, I found out that the SIM is not recognized on **any** ROMs, both stock and custom ones. I installed stock GPI2 via Odin - nope, then tried to install [Exodus](https://forum.xda-developers.com/galaxy-s4-sprint/orig-development/rom-team-exodus-jfltespr-t3135862) - nothing, even my own TWRP backup didn't work!
This thing happened after installing of your jdcteam_jdc_jflte-6-0-1-20170222-stable-zip. 
Can you explain this?

**Comment by smeroni68** [comment] 2017-03-05 16:22
A pure coincidence.
All custom rom on S4 do not touch the firmware, this is why we write in OP that latest firmware of modem must be installed separately. If you confirm that no one rom (custom and stock) will recognise anymore your sim, i can imagine that the hw sim module do not contact the sim chip anymore. That's my explanation as you requested.

Solution: search around for a new sim reader module (10$) and provide the exchange. Good luck.

**Comment by Suncatcher** [comment] 2017-03-05 19:52
It seems you're right. Will investigate further.

**Comment by smeroni68** [comment] 2017-03-05 19:55
There is another possibility: you may have lost IMEI...

EDIT: go on phone info and check if IMEI is there or is null...

**Comment by rigo9** [comment] 2017-03-07 15:02
I am having the same No sim card detection issue on almost all the Roms I have tried so far including this one. Sim only works with stock and that too after selecting gsm in network settings. Any fix for this? My Baseband is L720VPSGPL1.

**Comment by Suncatcher** [comment] 2017-03-07 15:35
> EDIT: go on phone info and check if IMEI is there or is null...

IMEI is showed.

**Comment by Suncatcher** [comment] 2017-03-07 17:32
> I am having the same No sim card detection issue on almost all the Roms I have tried so far including this one. Sim only works with stock and that too after selecting gsm in network settings. Any fix for this? My Baseband is L720VPSGPL1.

Holy shit! You're damn right! It's just should be changed to GSM and that's it! It works on stock!

> search around for a new sim reader module (10$) and provide the exchange

The problem has nothing to do with SIM module. The problem is with your implicit hardware LTE-enablement. Otherwise why the hell it affects other ROMs? I couldn't even think about it.

**Comment by rredford** [comment] 2017-03-10 21:32
I fixed mine by using 2 clear tape covers on top of SIM card. Worked fine most times. I think foam on top would fix it for good also.

**Comment by B--B** [comment] 2017-04-03 20:03
This issue belongs to MM, but next release will be the last, so i close this as MM reached the EOL, N is our stable release now, and unfortunately i have no time to keep two different ROMs alive for multiple devices, BTW with N stable and bug free (wifi hotspot will be fixed in next upcoming release) i don't see the sense to stay with an older android release and OMS working only in legacy mode

**Closed as completed by B--B** 2017-04-03 20:03 UTC
