### ISSUE TITLE
Pandora Tries to load but crashes. 

### ISSUE THREAD

**Issue by ke4clu** [AOSP-JF-MM/issue_tracking_aosp#87] opened 2016-08-03 19:09 UTC
Phone model: M919
Baseband version: M919UVUFOK3
ROM version: AOSP-6.0-20160726-jflte.zip
GApps Package: Open GApps Nano 20160803

Did you do a clean install for the currently installed build? yes

Did you reboot after having the issue? yes
Did you do any system modification? no
Did you flash another kernel? no
Did you install Xposed framework? no

Pandora tries to load but crashes and exits.   Work flawlessly with AOSP-6.0-20160709-jflte.zip

**Comment by codeseven58** [comment] 2016-08-04 03:15
I can verify this. here's my log. http://pastebin.com/n8wVEK07 . seems like the issue is with a missing class or file? line 250

> Caused by: java.lang.ClassNotFoundException: Didn't find class "android.webkit.ServiceWorkerController" on path: DexPathList[[zip file "/system/app/webview/webview.apk"],nativeLibraryDirectories=[/system/app/webview/lib/arm, /system/app/webview/webview.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]

I want to add that if i startup pandora, wait for the splash screen, and immediately hit the home button. music will play until I try to load pandora to change stations or something.

**Comment by ke4clu** [comment] 2016-08-04 10:58
Thanks for the quit response. 
Same here with Pandora will start to play unless I close the error popup. 
So what's the remedy?

**Comment by ke4clu** [comment] 2016-08-04 12:54
OK.  After browsing my device I do find Webview at /system/app/webview/webview.apk is there.

**Comment by ke4clu** [comment] 2016-08-05 16:07
I have the same issue with Pandora starting to play until I close the error box.   I don't know how long it would play because I always close the box:)

**Comment by codeseven58** [comment] 2016-08-15 02:23
2016/08/13 seems to be running pristinely for me, I haven't had any issues at all whatsoever in fact. I would suggest closing this issue if Ke4clu isn't having issues as well.

**Comment by ke4clu** [comment] 2016-08-15 11:47
codeseven58 ,
You were having the same issue as me.  What did you do to resolve it.

**Comment by ke4clu** [comment] 2016-08-15 11:49
I had back rev-ed to 2016-07-09 until I read you post.   I restored a backup of 2016-07-29 and the problem persists.

**Comment by smeroni68** [comment] 2016-08-15 13:17
Did you have files on external sd? If yes, have you tried to backup your files and format the sd?

**Comment by B--B** [comment] 2016-08-15 14:21
Update the ROM to latest public release, not 2016/07/29 version

**Comment by ke4clu** [comment] 2016-08-15 22:48
Link to latest public please.

**Comment by FernBch** [comment] 2016-08-15 23:10
It's in the OP on xda, as always.

https://romhut.com/roms/aosp-jf-6-0

**Comment by ke4clu** [comment] 2016-08-16 18:38
Thanks for the information guys.   After applying the recommendation from BB--BB and installing 20160812 all is well.

**Closed as completed** 2016-08-16 18:38 UTC
