### ISSUE TITLE
Offline Charging Broken on Xiaomi Mi5

### ISSUE THREAD

**Issue by style2345** [AOSP-JF-MM/issue_tracking_aosp#94] opened 2017-03-16 10:25 UTC
When Device is in Switch Off Condion & Connect to Charger then it Shows ( ??/100 )

ROM Version = [JDCTeam][7.1.1][12 March] 20170312 - Stable 2

Device = Xiaomi Mi5

**Comment by B--B** [comment] 2017-03-16 20:30
Thanks for the report
Fixed by this https://github.com/AOSP-JF-MM/platform_device_xiaomi_gemini/commit/61866708957ddb57c50c15fd3d66cabab4d8c6d5 and this https://github.com/AOSP-JF-MM/platform_system_core/commit/92d71cb83cac5edd18561808c0f40c2f2ef06f11
BTW charging function works in public release, which is the most important thing, only the charging images were missing
Regarding battery percentage it's a caf change, i've merged that too, tested now and it' s working fine
Please provide us some logs for the other bug you opened as i don't have any disconnection issues and i'm not able to reproduce your problem

**Closed as completed by B--B** 2017-03-16 20:30 UTC

**Comment by style2345** [comment] 2017-03-17 10:38
Rebuild the Rom With this Charging Image Patch Or Provide OTA Update 

Thanks ..

**Comment by smeroni68** [comment] 2017-03-17 10:45
Internal build already running... PM me on xda account...

**Comment by style2345** [comment] 2017-04-03 19:14
This issue has been fixed in

ROM Version = [JDCTeam][7.1.1][28 March][Substratum][EAS] - Stable 3

Thanks
